# Generated by Django 4.2.6 on 2023-10-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
